//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendsConfig) DeepCopyInto(out *BackendsConfig) {
	*out = *in
	out.LocalFile = in.LocalFile
	in.InfluxDB.DeepCopyInto(&out.InfluxDB)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendsConfig.
func (in *BackendsConfig) DeepCopy() *BackendsConfig {
	if in == nil {
		return nil
	}
	out := new(BackendsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.HttpServer = in.HttpServer
	in.Backends.DeepCopyInto(&out.Backends)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpAuthConfig) DeepCopyInto(out *HttpAuthConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpAuthConfig.
func (in *HttpAuthConfig) DeepCopy() *HttpAuthConfig {
	if in == nil {
		return nil
	}
	out := new(HttpAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpServerConfig) DeepCopyInto(out *HttpServerConfig) {
	*out = *in
	out.TLS = in.TLS
	out.Auth = in.Auth
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpServerConfig.
func (in *HttpServerConfig) DeepCopy() *HttpServerConfig {
	if in == nil {
		return nil
	}
	out := new(HttpServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpTLSConfig) DeepCopyInto(out *HttpTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpTLSConfig.
func (in *HttpTLSConfig) DeepCopy() *HttpTLSConfig {
	if in == nil {
		return nil
	}
	out := new(HttpTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxdbBackendConfig) DeepCopyInto(out *InfluxdbBackendConfig) {
	*out = *in
	out.BucketNames = in.BucketNames
	if in.StaticTags != nil {
		in, out := &in.StaticTags, &out.StaticTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxdbBackendConfig.
func (in *InfluxdbBackendConfig) DeepCopy() *InfluxdbBackendConfig {
	if in == nil {
		return nil
	}
	out := new(InfluxdbBackendConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxdbBucketNamesConfig) DeepCopyInto(out *InfluxdbBucketNamesConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxdbBucketNamesConfig.
func (in *InfluxdbBucketNamesConfig) DeepCopy() *InfluxdbBucketNamesConfig {
	if in == nil {
		return nil
	}
	out := new(InfluxdbBucketNamesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalFileBackendConfig) DeepCopyInto(out *LocalFileBackendConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalFileBackendConfig.
func (in *LocalFileBackendConfig) DeepCopy() *LocalFileBackendConfig {
	if in == nil {
		return nil
	}
	out := new(LocalFileBackendConfig)
	in.DeepCopyInto(out)
	return out
}
