name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run linters
        uses: golangci/golangci-lint-action@v2

  test:
    strategy:
      matrix:
        go-version: [1.17]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -v -coverprofile=coverage.txt -covermode=count ./...

      - name: Push code coverage to Codecov
        uses: codecov/codecov-action@v2
        # Push code coverage only for one of the environments
        if: matrix.platform == 'ubuntu-latest'
        with:
          files: ./coverage.txt
