name: Release

on:
  push:
    branches: [ main ]
    tags:
      - '*'

  # Allow manual run.
  workflow_dispatch:
    inputs:
      push_git_hash_tag:
        description: Push Git hash image tag
        default: false
        type: boolean

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
      git_hash: ${{ steps.git_hash.outputs.GIT_HASH }}
      go_version: ${{ steps.go_version.outputs.GO_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Get the tag
        id: tag_name
        run: echo "TAG_NAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Get the Git hash
        id: git_hash
        run: echo "GIT_HASH=$(git rev-parse HEAD | cut -c1-12)" >> $GITHUB_OUTPUT
      - name: Determine Go version from go.mod
        id: go_version
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_OUTPUT

  # Build and push docker image.
  release-docker:
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.metadata.outputs.go_version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Prepare image distribution name
        run: echo "IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/apple-health-ingester" >> $GITHUB_ENV

      - name: Prepare image tags
        run: |
          TAGS=()
          if [[ "${{ needs.metadata.outputs.tag_name != '' }}" == 'true' ]]; then
            # Add Git tag and latest image tags, only on new tags.
            TAGS+=('${{ env.IMAGE }}:${{ needs.metadata.outputs.tag_name }}' '${{ env.IMAGE }}:latest')
          elif [[ "${{ needs.metadata.outputs.git_hash != '' && inputs.push_git_hash_tag }}" == 'true' ]]; then
            # Push to image tag given by 12-character git hash.
            TAGS+=('${{ env.IMAGE }}:${{ needs.metadata.outputs.git_hash }}')
          elif [[ "${{ github.ref == 'refs/heads/main' }}" == 'true' ]]; then
            # Otherwise push to nightly tag on main branch pushes.
            TAGS+=('${{ env.IMAGE }}:nightly')
          fi
          echo "Will push the following tags: $TAGS"
          IFS=,; echo "IMAGE_TAGS=${TAGS[*]}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ env.IMAGE_TAGS != '' }}
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_TAGS }}

  # Release artifacts only on new tags.
  release-artifacts:
    strategy:
      matrix:
        GOOS: [linux, darwin]
        GOARCH: [arm, arm64, amd64]
        exclude:
          - GOOS: darwin
            GOARCH: arm

    runs-on: ubuntu-latest
    needs: metadata
    if: needs.metadata.outputs.tag_name != ''
    env:
      executable: apple-health-ingester-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.metadata.outputs.go_version }}

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test
        run: go test -v ./...

      - name: Build
        run: env GOOS=${{matrix.GOOS}} GOARCH=${{matrix.GOARCH}} go build -v -o ${{env.executable}} ./cmd/ingester/...

      - name: Create or update release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{env.executable}}
          tag: ${{ needs.metadata.outputs.tag_name }}
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
