name: Release Nightly Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      use_nightly_tag:
        description: Push "nightly" image tag
        default: true
        type: boolean
      use_git_hash_tag:
        description: Push Git hash image tag
        default: false
        type: boolean

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      git_hash: ${{ steps.git_hash.outputs.GIT_HASH }}
      go_version: ${{ steps.go_version.outputs.GO_VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Get the Git hash
        id: git_hash
        run: echo "GIT_HASH=$(git rev-parse HEAD | cut -c1-12)" >> $GITHUB_OUTPUT
      - name: Determine Go version from go.mod
        id: go_version
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_OUTPUT

  release-docker:
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.metadata.outputs.go_version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Prepare image distribution name
        run: echo "IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/apple-health-ingester" >> $GITHUB_ENV

      - name: Make tags
        run: |
          TAGS=()
          if [[ "${{ inputs.use_nightly_tag }}" == 'true' ]]; then
            TAGS+=('${{ env.IMAGE }}:nightly')
          fi
          if [[ "${{ inputs.use_git_hash_tag }}" == 'true' ]]; then
            TAGS+=('${{ env.IMAGE }}:${{ needs.metadata.outputs.git_hash }}')
          fi
          echo "Will push the following tags: $TAGS"
          IFS=,; echo "IMAGE_TAGS=${TAGS[*]}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_TAGS }}
